version: "3.9"

services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: always
    network_mode: "host"
    volumes:
      - ./livekit-server/livekit.yaml:/etc/livekit.yaml

  redis:
    image: redis:7-alpine
    restart: always
    network_mode: "host"
    command: redis-server --port 6380

  agent:
    build: 
      context: ./agent
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    depends_on:
      - livekit
    environment:
      - LIVEKIT_URL=ws://127.0.0.1:7880
    env_file:
      - ./agent/.env

